# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 661181c20a8884daed7f0a22e3ae028a3d232b4e

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 661181c20a8884daed7f0a22e3ae028a3d232b4e

{ "title": "Стол IKEA",
  "status": "CLOSED"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token c7a2fc541c9acb80d5f35f84f83427642d342c5d

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-10-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json
