# Generated by Django 4.1.4 on 2022-12-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
